on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write


jobs:
  benchmark:
    name: Performance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: x64

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'

      - name: Install Julia deps
        shell: bash
        run: julia -e 'using Pkg; Pkg.add("JSON"); Pkg.add("Jabalizer")'

      - name: Upgrade pip
        shell: bash
        run: python -m pip install --upgrade pip

      - name: Install deps
        shell: bash
        run: python -m pip install -e '.[dev]'

      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Run benchmark
        run: python -m pytest benchmarks --benchmark-json output.json
      # gh-pages branch is updated and pushed automatically with extracted benchmark data
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchq Benchmarking
          tool: 'pytest'
          output-file-path: output.json
          auto-push: false
          ref: "${GITHUB_SHA}"
      - name: Push benchmark result
        run: git push 'https://${{ secrets.GITHUB_TOKEN }}@github.com/zapatacomputing/benchq.git' gh-pages:gh-pages
